### ISSUE TITLE
Not work currently?

### ISSUE THREAD

**Issue by thekevin-cisco** [efigence/yabeda-grape#7]
When trying to hit an existing working endpoint after enabling `yabeda-grape`:

```json
{"response_type":"error","details":"Prometheus requires all used tags to be declared at metric registration time. Please add `tags` option to the declaration of metric `grape_requests_total`. Error: labels must have the same signature (keys given: [:method, :path, :status] vs. keys expected: []"}
```

Is there something more we need to do to get this to work?

**Comment by Prorok64b** [comment]
@kevine-voicera version 0.1.1 should works, but also you can try 0.1.2. I added metric tags there.
It was tested with "prometheus-2.12.0.linux-amd64".
